language: go
sudo: false

go:
  - 1.4.3
  - 1.5.1

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go get github.com/constabulary/gb/...
  - gb info
  - gb vendor restore

script:
  - gb test -v
  - go run build.go
