language: go
sudo: false

go:
  - 1.x

install:
  - go version
  - export PATH="$PATH:$GOPATH/bin"
  - go get -u golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/goimports

script:
  - GO111MODULE=on go build -mod=vendor
  - GO111MODULE=on go test ./...
  - GO111MODULE=on go run -mod=vendor build.go -v -T
  - diff <(goimports -d *.go) <(printf "")

after_success:
  - diff <(golint .) <(printf "")
