language: go
sudo: false

go:
  - 1.x

install:
  - go version
  - export PATH="$PATH:$GOPATH/bin"
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports

script:
  - go build -mod=vendor
  - go test -v
  - go run -mod=vendor build.go -v -T
  - diff <(goimports -d *.go) <(printf "")

after_success:
  - diff <(golint .) <(printf "")
